# Libraries

In [ ]:
import numpy

# Code

## Example 1

In [ ]:
corpus = [
    "The quick brown fox jumped over the lazy dog",
    "She sells seashells by the seashore",
    "Peter Piper picked a peck of pickled peppers",
]

In [ ]:
unique_words = set()
for sentence in corpus:
  for word in sentence.split():
    unique_words.add(word.lower())

In [ ]:
word_to_index = {}
for i, word in enumerate(unique_words):
  word_to_index[word] = i

In [ ]:
one_hot_vectors = []
for sentence in corpus:
  sentence_vectors = []
  for word in sentence.split():
    vector = numpy.zeros(len(unique_words))
    vector[word_to_index[word.lower()]] = 1
    sentence_vectors.append(vector)
  one_hot_vectors.append(sentence_vectors)

## Result 1

In [ ]:
print("One-hot encoding vectors for the first sentence:")
for vector in one_hot_vectors[0]:
  print(vector)

## Example 2

In [ ]:
corpus = [
    "The cat sat on the mat.",
    "The dog chased the cat.",
    "The mat was soft and fluffy.",
]

In [ ]:
unique_words = set()
for sentence in corpus:
  for word in sentence.split():
    unique_words.add(word)

In [ ]:
word_to_index = {}
for i, word in enumerate(unique_words):
  word_to_index[word] = i

In [ ]:
one_hot_vectors = []
for sentence in corpus:
  sentence_vectors = []
  for word in sentence.split():
    vector = numpy.zeros(len(unique_words))
    vector[word_to_index[word.lower()]] = 1
    sentence_vectors.append(vector)
  one_hot_vectors.append(sentence_vectors)

## Result 2

In [ ]:
print("One-hot encoding vectors for the first sentence:")
for vector in one_hot_vectors[0]:
  print(vector)

One-hot encoding vectors for the first sentence:
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
